const STORAGE_KEY = "affiliatiTopHouse";
const VENDITORI_REGISTRATI = ["Antonio Attardi", "Davide Marino", "Fabio Magnago", "Gabriele Straniero", "Giuseppe Maresca", "Lamine Tall", "Morena Caccavo", "Studio Cian"];
const STATI = ["Attivo", "Non attivo", "In valutazione"];
function testo(v){ return String(v || "").trim(); }
function leggi(){ try{ const d = JSON.parse(localStorage.getItem(STORAGE_KEY)); return Array.isArray(d) ? d.map(normalizzaAffiliato) : []; }catch(e){ return []; } }
function salva(lista){ localStorage.setItem(STORAGE_KEY, JSON.stringify(lista)); }
function esc(v){ return testo(v).replace(/[&<>'"]/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c])); }
function badge(v){ return `<span class="badge ${testo(v).toLowerCase().replaceAll(" ", "-")}">${esc(v || "-")}</span>`; }
function normalizzaVenditore(v){ const t = testo(v); return VENDITORI_REGISTRATI.find(x => x.toLowerCase() === t.toLowerCase()) || t; }
function normalizzaAffiliato(a){ const nome = testo(a.nomeAffiliato || a.nome || a.nomeAttivita); const cognome = testo(a.cognomeRagioneSociale || a.cognome || a.ragioneSociale || a.citta); return { id:Number(a.id || Date.now()), nomeAffiliato:nome, cognomeRagioneSociale:cognome, telefono:testo(a.telefono), email:testo(a.email), venditoreCollegato:normalizzaVenditore(a.venditoreCollegato || a.venditore), zona:testo(a.zona || a.citta), stato: STATI.includes(testo(a.stato)) ? testo(a.stato) : (testo(a.stato) === "Da contattare" ? "In valutazione" : "Attivo"), note:testo(a.note), dataInserimento:testo(a.dataInserimento) || new Date().toISOString() }; }
function nomeCompleto(a){ return [a.nomeAffiliato, a.cognomeRagioneSociale].filter(Boolean).join(" "); }
function popolaVenditori(){ const opts = VENDITORI_REGISTRATI.map(v => `<option value="${esc(v)}">${esc(v)}</option>`).join(""); venditoreCollegato.innerHTML = `<option value="">Seleziona venditore</option>${opts}`; filterVendor.innerHTML = `<option value="">Tutti i venditori</option>${opts}`; }
function aggiornaKpi(lista){ kpiTotale.innerText = lista.length; kpiAttivi.innerText = lista.filter(a => a.stato === "Attivo").length; kpiNonAttivi.innerText = lista.filter(a => a.stato === "Non attivo").length; kpiInValutazione.innerText = lista.filter(a => a.stato === "In valutazione").length; }
function filtra(lista){ const q = testo(searchText.value).toLowerCase(), vend = testo(filterVendor.value), statoFiltro = testo(filterStatus.value); return lista.filter(a => { const hay = `${nomeCompleto(a)} ${a.telefono} ${a.email} ${a.venditoreCollegato} ${a.zona} ${a.stato} ${a.note}`.toLowerCase(); return (!q || hay.includes(q)) && (!vend || a.venditoreCollegato === vend) && (!statoFiltro || a.stato === statoFiltro); }); }
function render(){ const lista = leggi(); aggiornaKpi(lista); const filtrati = filtra(lista); affiliatesBody.innerHTML = filtrati.length ? filtrati.map(a => `<tr><td><strong>${esc(nomeCompleto(a))}</strong></td><td>${esc(a.telefono)}</td><td>${esc(a.email)}</td><td>${esc(a.venditoreCollegato)}</td><td>${esc(a.zona)}</td><td>${badge(a.stato)}</td><td>${esc(a.note)}</td><td><div class="action-buttons"><button class="edit-btn" onclick="modifica(${a.id})">Modifica</button><button class="delete-btn" onclick="elimina(${a.id})">Elimina</button></div></td></tr>`).join("") : `<tr><td colspan="8" style="text-align:center; padding:30px; color:#6b7280; font-weight:bold;">Nessun affiliato trovato.</td></tr>`; }
function resetForm(){ affiliateForm.reset(); affiliateId.value = ""; saveAffiliateBtn.innerText = "Salva affiliato"; }
function modifica(id){ const a = leggi().find(x => Number(x.id) === Number(id)); if(!a){ return; } affiliateId.value = a.id; nomeAffiliato.value = a.nomeAffiliato; cognomeRagioneSociale.value = a.cognomeRagioneSociale; telefono.value = a.telefono; email.value = a.email; venditoreCollegato.value = a.venditoreCollegato; zona.value = a.zona; stato.value = a.stato; note.value = a.note; saveAffiliateBtn.innerText = "Aggiorna affiliato"; window.scrollTo({top:0, behavior:"smooth"}); }
function elimina(id){ if(!confirm("Eliminare questo affiliato?")){ return; } salva(leggi().filter(a => Number(a.id) !== Number(id))); render(); }
function exportAffiliates(){ const righe = filtra(leggi()).map(a => `<tr><td>${esc(nomeCompleto(a))}</td><td>${esc(a.telefono)}</td><td>${esc(a.email)}</td><td>${esc(a.venditoreCollegato)}</td><td>${esc(a.zona)}</td><td>${esc(a.stato)}</td><td>${esc(a.note)}</td><td>${esc(a.dataInserimento)}</td></tr>`).join(""); const html = `<html><head><meta charset="UTF-8"></head><body><h1>TOP HOUSE - Affiliati</h1><table border="1"><thead><tr><th>Nome affiliato</th><th>Telefono</th><th>Email</th><th>Venditore</th><th>Zona</th><th>Stato</th><th>Note</th><th>Data inserimento</th></tr></thead><tbody>${righe}</tbody></table></body></html>`; const blob = new Blob([html], {type:"application/vnd.ms-excel;charset=utf-8;"}); const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = "affiliati-top-house.xls"; link.click(); }
affiliateForm.addEventListener("submit", e => { e.preventDefault(); const lista = leggi(); const id = affiliateId.value; const precedente = lista.find(a => Number(a.id) === Number(id)); const dati = normalizzaAffiliato({ id: id ? Number(id) : Date.now(), nomeAffiliato:nomeAffiliato.value, cognomeRagioneSociale:cognomeRagioneSociale.value, telefono:telefono.value, email:email.value, venditoreCollegato:venditoreCollegato.value, zona:zona.value, stato:stato.value, note:note.value, dataInserimento: precedente?.dataInserimento || new Date().toISOString() }); const i = lista.findIndex(a => Number(a.id) === Number(id)); if(i >= 0){ lista[i] = dati; }else{ lista.push(dati); } salva(lista); resetForm(); render(); });
cancelEditBtn.addEventListener("click", resetForm); exportAffiliatesBtn.addEventListener("click", exportAffiliates); resetAffiliateFiltersBtn.addEventListener("click", () => { searchText.value=""; filterVendor.value=""; filterStatus.value=""; render(); }); ["searchText","filterVendor","filterStatus"].forEach(id => document.getElementById(id).addEventListener("input", render)); popolaVenditori(); salva(leggi()); render();
