import { FIREBASE_COLLECTIONS, migrateLocalStorageToFirestore, syncAllFromFirestore } from "./firebase-data.js";
const BACKUP_KEYS = ["contrattiTopHouse", "investimentiTopHouse", "attivitaTopHouse", "documentiTopHouse", "affiliatiTopHouse", "statiVenditoriTopHouse"];
const VENDITORI_TOTALI = 8;
const PARTNER_TOTALI = 8;
function leggiValore(key){ try{ return JSON.parse(localStorage.getItem(key)); }catch(e){ return null; } }
function leggiLista(key){ const d = leggiValore(key); return Array.isArray(d) ? d : []; }
function aggiornaConteggi(){ countContratti.innerText = leggiLista("contrattiTopHouse").length; countInvestimenti.innerText = leggiLista("investimentiTopHouse").length; countAttivita.innerText = leggiLista("attivitaTopHouse").length; countDocumenti.innerText = leggiLista("documentiTopHouse").length; countAffiliati.innerText = leggiLista("affiliatiTopHouse").length; countVenditori.innerText = VENDITORI_TOTALI; countPartner.innerText = PARTNER_TOTALI; ultimoBackup.innerText = localStorage.getItem("ultimoBackupTopHouse") || "-"; }
function esporta(){ const oggi = new Date().toISOString().slice(0,10); const backup = { gestionale:"TOP HOUSE GESTIONALE", esportatoIl: new Date().toISOString() }; BACKUP_KEYS.forEach(k => backup[k] = leggiValore(k) ?? (k === "statiVenditoriTopHouse" ? {} : [])); const blob = new Blob([JSON.stringify(backup, null, 2)], { type:"application/json" }); const a = document.createElement("a"); a.href = URL.createObjectURL(blob); a.download = `backup-top-house-gestionale-${oggi}.json`; a.click(); URL.revokeObjectURL(a.href); localStorage.setItem("ultimoBackupTopHouse", oggi); aggiornaConteggi(); }
function importa(){ const file = importFile.files[0]; if(!file){ alert("Seleziona un file JSON di backup TOP HOUSE."); return; } const reader = new FileReader(); reader.onload = () => { try{ const data = JSON.parse(reader.result); const ok = confirm("Importare questo backup? Le chiavi dati TOP HOUSE presenti nel browser saranno sovrascritte con quelle contenute nel file."); if(!ok){ return; } BACKUP_KEYS.forEach(k => { if(k in data){ const attesoOggetto = k === "statiVenditoriTopHouse"; const valido = attesoOggetto ? data[k] && typeof data[k] === "object" && !Array.isArray(data[k]) : Array.isArray(data[k]); if(valido){ localStorage.setItem(k, JSON.stringify(data[k])); } } }); aggiornaConteggi(); alert("Backup importato correttamente."); }catch(e){ alert("File JSON non valido o non leggibile."); } }; reader.readAsText(file); }
function resetKey(key){ const nomi = { contrattiTopHouse:"contratti", investimentiTopHouse:"investimenti", attivitaTopHouse:"attività", documentiTopHouse:"documenti", affiliatiTopHouse:"affiliati" }; if(!confirm(`Vuoi davvero svuotare ${nomi[key] || key}? L'azione riguarda solo questa sezione.`)){ return; } localStorage.setItem(key, JSON.stringify([])); aggiornaConteggi(); }
exportBackupBtn.addEventListener("click", esporta); importBackupBtn.addEventListener("click", importa); document.querySelectorAll("[data-reset]").forEach(btn => btn.addEventListener("click", () => resetKey(btn.dataset.reset))); aggiornaConteggi();

function setFirebaseStatus(message, type){ const el = document.getElementById("firebaseStatus"); if(el){ el.textContent = message; el.className = `firebase-status ${type || ""}`.trim(); } }
document.querySelectorAll("[data-migrate]").forEach(btn => btn.addEventListener("click", async () => { const key = btn.dataset.migrate; btn.disabled = true; try{ const result = await migrateLocalStorageToFirestore(key, FIREBASE_COLLECTIONS[key]); setFirebaseStatus(`${result.migrated} elementi migrati su Firebase`, "online"); aggiornaConteggi(); }catch(error){ console.error(error); setFirebaseStatus("Errore Firebase", "error"); } finally{ btn.disabled = false; } }));
if(document.getElementById("syncFirebaseBtn")){ syncFirebaseBtn.addEventListener("click", async () => { syncFirebaseBtn.disabled = true; try{ await syncAllFromFirestore(); setFirebaseStatus("Dati sincronizzati", "online"); aggiornaConteggi(); }catch(error){ console.error(error); setFirebaseStatus("Errore Firebase", "error"); } finally{ syncFirebaseBtn.disabled = false; } }); }
