const KEY="topHouseCRM";const defaultData={contracts:[],affiliates:[{id:1,name:"Esempio CAF",type:"CAF",percent:10,status:"Attivo"},{id:2,name:"Esempio Agenzia",type:"Agenzia",percent:8,status:"Attivo"}],plans:[{id:1,name:"Piano Compensi STD",description:"Piano personale attualmente associato al venditore",updated:"Ottobre 2026"}]};let data=load();let currentPage="dashboard";
function load(){try{return {...defaultData,...JSON.parse(localStorage.getItem(KEY)||"{}")}}catch{return structuredClone(defaultData)}}function save(){localStorage.setItem(KEY,JSON.stringify(data))}
function money(n){return new Intl.NumberFormat("it-IT",{style:"currency",currency:"EUR"}).format(n||0)}
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function toast(t){const x=document.querySelector("#toast");x.textContent=t;x.classList.add("show");setTimeout(()=>x.classList.remove("show"),2200)}
function setPage(page){currentPage=page;document.querySelectorAll(".nav-item").forEach(x=>x.classList.toggle("active",x.dataset.page===page));document.querySelector("#page-title").textContent={dashboard:"Dashboard",contracts:"Contratti",affiliates:"Affiliati",plans:"Piano compensi",status:"Stato contratti"}[page];render()}
function render(){const el=document.querySelector("#page-content");if(currentPage==="dashboard")el.innerHTML=dashboard();if(currentPage==="contracts")el.innerHTML=contracts();if(currentPage==="affiliates")el.innerHTML=affiliates();if(currentPage==="plans")el.innerHTML=plans();if(currentPage==="status")el.innerHTML=statusPage();bindPage()}
function dashboard(){const total=data.contracts.length, ok=data.contracts.filter(x=>x.status==="OK").length, pending=data.contracts.filter(x=>x.status!=="OK"&&x.status!=="KO").length;return `<section class="stats"><div class="stat"><div class="stat-label">I miei contratti</div><div class="stat-value">${total}</div><div class="stat-note">Totale inserito</div></div><div class="stat"><div class="stat-label">Contratti OK</div><div class="stat-value">${ok}</div><div class="stat-note">Pratiche valide</div></div><div class="stat"><div class="stat-label">In lavorazione</div><div class="stat-value">${pending}</div><div class="stat-note">Da verificare</div></div><div class="stat"><div class="stat-label">Affiliati</div><div class="stat-value">${data.affiliates.length}</div><div class="stat-note">CAF, agenzie e venditori</div></div></section><div class="grid-2"><section class="panel"><div class="panel-head"><div><h2>Ultimi contratti</h2><div class="panel-sub">Le tue ultime pratiche inserite</div></div><button class="link-btn" data-go="contracts">Vedi tutti →</button></div>${contractTable(data.contracts.slice(-7).reverse())}</section><section class="panel"><div class="panel-head"><div><h2>Riepilogo</h2><div class="panel-sub">Informazioni rapide</div></div></div><div style="display:grid;gap:14px"><div><b>Servizi</b><div class="panel-sub">Luce, Gas, Fibra e altri servizi potranno essere aggiunti senza cambiare la struttura.</div></div><div><b>Affiliazioni</b><div class="panel-sub">Qui verranno collegati i soggetti che generano una percentuale per te.</div></div><div><b>Piano compensi</b><div class="panel-sub">Accesso al piano personale, separato dai dati degli altri venditori.</div></div></div></section></div>`}
function contractTable(list){if(!list.length)return '<div class="empty">Nessun contratto ancora. Inserisci il primo dalla sezione Contratti.</div>';return `<div class="table-wrap"><table><thead><tr><th>Cliente</th><th>Data</th><th>Servizio</th><th>Gestore</th><th>Stato</th></tr></thead><tbody>${list.map(c=>`<tr><td><b>${esc(c.name)}</b></td><td>${esc(c.date)}</td><td>${esc(c.service)}</td><td>${esc(c.manager)}</td><td><span class="badge ${c.status==="OK"?"ok":c.status==="KO"?"ko":"pending"}">${esc(c.status)}</span></td></tr>`).join("")}</tbody></table></div>`}
function contracts(){return `<section class="panel"><div class="panel-head"><div><h2>Contratti</h2><div class="panel-sub">Inserisci e consulta esclusivamente le tue pratiche.</div></div><button class="primary" id="new-contract">+ Nuovo contratto</button></div><div class="filters"><input class="input" id="contract-search" placeholder="Cerca cliente..."><select class="select" id="contract-service"><option value="">Tutti i servizi</option><option>Luce</option><option>Gas</option><option>Luce + Gas</option><option>Fibra</option><option>Fotovoltaico</option><option>Altro</option></select></div><div id="contracts-table">${contractTable(data.contracts.slice().reverse())}</div></section>`}
function affiliates(){return `<section class="panel"><div class="panel-head"><div><h2>I miei affiliati</h2><div class="panel-sub">CAF, agenzie, venditori o altri soggetti collegati alla tua produzione.</div></div><button class="primary" id="new-affiliate">+ Nuovo affiliato</button></div><div class="section-grid">${data.affiliates.map(a=>`<article class="affiliate-card"><div class="affiliate-top"><div><div class="affiliate-name">${esc(a.name)}</div><div class="affiliate-type">${esc(a.type)} · ${esc(a.status)}</div></div><div class="percent">${esc(a.percent)}%</div></div><div class="panel-sub" style="margin-top:16px">Percentuale riconosciuta sulle pratiche collegate.</div></article>`).join("")||'<div class="empty">Nessun affiliato.</div>'}</div></section>`}
function plans(){return `<section class="panel"><div class="panel-head"><div><h2>Il mio piano compensi</h2><div class="panel-sub">Area personale del venditore.</div></div></div><div class="section-grid">${data.plans.map(p=>`<article class="affiliate-card"><div class="affiliate-name">${esc(p.name)}</div><div class="affiliate-type">${esc(p.description)}</div><div style="margin-top:18px;font-size:13px"><b>Ultimo aggiornamento:</b> ${esc(p.updated)}</div><button class="secondary" style="margin-top:18px">Apri piano</button></article>`).join("")}</div></section>`}
function statusPage(){
 const all=data.contracts.slice().reverse();
 const counts={Inserito:0,"In lavorazione":0,OK:0,KO:0,Storno:0};
 all.forEach(c=>{if(counts[c.status]!==undefined)counts[c.status]++});
 return `<section class="stats">
 <div class="stat"><div class="stat-label">Totale</div><div class="stat-value">${all.length}</div><div class="stat-note">Tutti i miei contratti</div></div>
 <div class="stat"><div class="stat-label">In lavorazione</div><div class="stat-value">${counts["In lavorazione"]+counts.Inserito}</div><div class="stat-note">Pratiche da verificare</div></div>
 <div class="stat"><div class="stat-label">OK</div><div class="stat-value">${counts.OK}</div><div class="stat-note">Contratti validati</div></div>
 <div class="stat"><div class="stat-label">KO / Storno</div><div class="stat-value">${counts.KO+counts.Storno}</div><div class="stat-note">Pratiche non valide</div></div>
 </section>
 <section class="panel"><div class="panel-head"><div><h2>Stato dei miei contratti</h2><div class="panel-sub">Monitoraggio delle pratiche inserite.</div></div>
 <select class="select" id="status-filter"><option value="">Tutti gli stati</option><option>Inserito</option><option>In lavorazione</option><option>OK</option><option>KO</option><option>Storno</option></select></div>
 <div id="status-table">${statusTable(all)}</div></section>`;
}
function statusTable(list){
 if(!list.length)return '<div class="empty">Nessun contratto trovato.</div>';
 return `<div class="table-wrap"><table><thead><tr><th>Cliente</th><th>Data firma</th><th>Servizio</th><th>Gestore</th><th>Città</th><th>RID</th><th>Stato</th></tr></thead><tbody>${list.map(c=>`<tr><td><b>${esc(c.name)}</b></td><td>${esc(c.date)}</td><td>${esc(c.service)}</td><td>${esc(c.manager)}</td><td>${esc(c.city)}</td><td>${esc(c.rid)}</td><td><span class="badge ${c.status==="OK"?"ok":c.status==="KO"||c.status==="Storno"?"ko":"pending"}">${esc(c.status)}</span></td></tr>`).join("")}</tbody></table></div>`;
}
function bindPage(){document.querySelectorAll("[data-go]").forEach(b=>b.onclick=()=>setPage(b.dataset.go));const nc=document.querySelector("#new-contract");if(nc)nc.onclick=()=>openContract();const nt=document.querySelector("#new-affiliate");if(nt)nt.onclick=()=>openAffiliate();const statusFilter=document.querySelector("#status-filter");if(statusFilter){statusFilter.onchange=()=>{let l=data.contracts.slice().reverse();if(statusFilter.value)l=l.filter(x=>x.status===statusFilter.value);document.querySelector("#status-table").innerHTML=statusTable(l)}}const search=document.querySelector("#contract-search"),service=document.querySelector("#contract-service");if(search){const filter=()=>{let l=data.contracts.slice().reverse();const q=search.value.toLowerCase();if(q)l=l.filter(x=>x.name.toLowerCase().includes(q));if(service.value)l=l.filter(x=>x.service===service.value);document.querySelector("#contracts-table").innerHTML=contractTable(l)};search.oninput=filter;service.onchange=filter}}
function modal(html){const wrap=document.createElement("div");wrap.className="modal-backdrop open";wrap.innerHTML=`<div class="modal">${html}</div>`;document.body.appendChild(wrap);return wrap}
function closeModal(m){m.remove()}
function openContract(){const m=modal(`<div class="modal-head"><h2>Nuovo contratto</h2><button class="close">×</button></div><form id="contract-form"><div class="form-grid"><div class="field"><label>Nome e cognome cliente</label><input class="input" name="name" required></div><div class="field"><label>Data firma</label><input class="input" type="date" name="date" required></div><div class="field"><label>RID</label><select class="select" name="rid"><option>RID</option><option>No RID</option></select></div><div class="field"><label>Servizio</label><select class="select" name="service" required><option>Luce</option><option>Gas</option><option>Luce + Gas</option><option>Fibra</option><option>Fotovoltaico</option><option>Altro</option></select></div><div class="field"><label>Gestore</label><input class="input" name="manager" placeholder="Es. Plenitude" required></div><div class="field"><label>Città</label><input class="input" name="city" required></div></div><div class="form-actions"><button type="button" class="secondary cancel">Annulla</button><button class="primary">Salva contratto</button></div></form>`);m.querySelector(".close").onclick=()=>closeModal(m);m.querySelector(".cancel").onclick=()=>closeModal(m);m.querySelector("form").onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);data.contracts.push({id:Date.now(),name:f.get("name"),date:f.get("date"),rid:f.get("rid"),service:f.get("service"),manager:f.get("manager"),city:f.get("city"),status:"In lavorazione"});save();closeModal(m);render();toast("Contratto inserito correttamente")}}
function openAffiliate(){const m=modal(`<div class="modal-head"><h2>Nuovo affiliato</h2><button class="close">×</button></div><form id="affiliate-form"><div class="form-grid"><div class="field"><label>Nome / Ragione sociale</label><input class="input" name="name" required></div><div class="field"><label>Tipo</label><select class="select" name="type"><option>CAF</option><option>Agenzia</option><option>Venditore</option><option>Altro</option></select></div><div class="field"><label>Percentuale</label><input class="input" name="percent" type="number" min="0" max="100" step=".1" required></div><div class="field"><label>Stato</label><select class="select" name="status"><option>Attivo</option><option>Inattivo</option></select></div></div><div class="form-actions"><button type="button" class="secondary cancel">Annulla</button><button class="primary">Salva affiliato</button></div></form>`);m.querySelector(".close").onclick=()=>closeModal(m);m.querySelector(".cancel").onclick=()=>closeModal(m);m.querySelector("form").onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);data.affiliates.push({id:Date.now(),name:f.get("name"),type:f.get("type"),percent:f.get("percent"),status:f.get("status")});save();closeModal(m);render();toast("Affiliato aggiunto")}}
document.querySelectorAll(".nav-item").forEach(b=>b.onclick=()=>setPage(b.dataset.page));document.querySelector("#new-contract-top").onclick=openContract;render();