let db=null;
let firestoreApi={};
let firebaseApp=null, authInstance=null, authApi=null, functionsApi=null, firebaseAuthUser=null;
let automationLogs=[];
let statsSelectedSeller="";

const KEY="topHouseCRM";
const SERVICES=["Luce","Gas","Luce + Gas","Fibra","Telefonia Mobile","Telefonia Fissa","Luce + Gas + Fibra","Fotovoltaico","Fotovoltaico + Accumulo","Caldaia","Climatizzatore","Pompa di calore","Infissi","Depuratore","Allarme","Wall Box","Altro"];
const MANAGERS=["A2A","ACEA","Alperia","Cogeme","Duferco","Enel","Enel Digital","Engie","GDE","Hera","Iren","Onova","S4","Simecom","Sorgenia","Stream","Unoenergy","Vivienergia","Plenitude","Union Energia","TIM","Fastweb","WindTre","Vodafone","Sky Wifi","WINDTRE","Altro"];
let SELLERS=["Lamine Tall","Gabriele Straniero","Francesco Cecchini","Hajar Sadiq","Sarah Cavedo","Dardan Gashi","Andrea Cerminare","Benedetto Cavallo"];
const STATUSES=["Inserito","In lavorazione","OK","KO","Storno"];
const SOURCES=["Affiliato","Venditore","Referenze","Sito","Social","Passaparola","Centro commerciale","Negozio","Altro"];
const defaultData={contracts:[],affiliates:[],leads:[],events:[],plans:[{id:1,name:"Piano Compensi STD",description:"Piano compensi personale",updated:"Ottobre 2026"}]};
let data=structuredClone(defaultData),currentPage="dashboard",currentUser=null,cloudUnsubscribe=null,cloudReady=false,currentProfile=null,userProfiles=[];
const ROLE_LABELS={admin:"Amministratore",manager:"Capo venditore",seller:"Venditore"};
const ROLE_NAMES={admin:"Admin",manager:"Capo venditore",seller:"Venditore"};
function isAdmin(){return currentProfile?.role==="admin"}
function isManager(){return currentProfile?.role==="manager"}
function visibleSellerNames(){if(isAdmin())return SELLERS;if(isManager())return [currentProfile.name,...userProfiles.filter(u=>u.managerUid===currentUser.uid&&u.active!==false).map(u=>u.name)].filter(Boolean);return [currentProfile?.name||currentProfile?.sellerName||""];}
function visibleData(){const names=new Set(visibleSellerNames());return {...data,contracts:data.contracts.filter(c=>names.has(c.seller)),leads:data.leads.filter(x=>names.has(x.seller)),events:data.events.filter(x=>!x.seller||names.has(x.seller))}}
function canManageSeller(name){return isAdmin()||isManager()&&visibleSellerNames().includes(name)}
async function loadProfiles(){const snap=await getDocs(collection(db,"users"));userProfiles=snap.docs.map(d=>({uid:d.id,...d.data()}));const names=userProfiles.filter(u=>u.active!==false&&u.name).map(u=>u.name);SELLERS=[...new Set([...SELLERS,...names])]}
async function ensureProfile(user){const ref=doc(db,"users",user.uid),snap=await getDoc(ref);if(snap.exists()){currentProfile={uid:user.uid,...snap.data()};return}
const existing=await getDocs(collection(db,"users"));const role=existing.empty?"admin":"seller";const profile={email:user.email||"",name:user.email?.split("@")[0]||"Venditore",sellerName:user.email?.split("@")[0]||"Venditore",role,managerUid:null,managerName:"",active:true,createdAt:serverTimestamp()};await setDoc(ref,profile);currentProfile={uid:user.uid,...profile};toast(role==="admin"?"Primo account impostato come Admin":"Account creato come Venditore")}
async function save(){
  localStorage.setItem(KEY,JSON.stringify(data));
  if(!db||!firestoreApi.setDoc)return;
  try{
    const {doc,setDoc,serverTimestamp}=firestoreApi;
    await setDoc(doc(db,"crmData","main"),{...data,updatedAt:serverTimestamp(),updatedBy:currentUser?.uid||"local-admin"},{merge:true});
  }catch(err){console.error("Firebase save error",err);toast("Salvato localmente · cloud non disponibile")}
}
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function money(n){return new Intl.NumberFormat("it-IT",{style:"currency",currency:"EUR"}).format(Number(n)||0)}
function toast(t){const x=document.querySelector("#toast");x.textContent=t;x.classList.add("show");setTimeout(()=>x.classList.remove("show"),2200)}
function options(arr,selected="",first=""){return (first?'<option value="">'+first+"</option>":"")+arr.map(x=>'<option '+(x===selected?"selected":"")+'>'+esc(x)+"</option>").join("")}
function setPage(p){if(p==="users"&&!isAdmin()&&!isManager())return toast("Area riservata ai responsabili");currentPage=p;document.querySelectorAll(".nav-item").forEach(x=>x.classList.toggle("active",x.dataset.page===p));document.querySelector("#page-title").textContent={dashboard:"Dashboard",contracts:"Contratti",clients:"I miei clienti",leads:"Lead",calendar:"Calendario",stats:"Statistiche",affiliates:"Affiliati",plans:"Piano compensi",status:"Stato contratti",users:"Utenti e ruoli",automations:"Automazioni email"}[p];render()}
function render(){const e=document.querySelector("#page-content"),fullData=data;data=visibleData();e.innerHTML=currentPage==="dashboard"?dashboard():currentPage==="contracts"?contracts():currentPage==="clients"?clients():currentPage==="leads"?leads():currentPage==="calendar"?calendar():currentPage==="stats"?statsPage():currentPage==="affiliates"?affiliates():currentPage==="plans"?plans():currentPage==="users"?usersPage():currentPage==="automations"?automationsPage():statusPage();data=fullData;bindPage()}
function dashboard(){const cs=data.contracts,total=cs.reduce((n,c)=>n+(c.service==="Luce + Gas"?2:1),0),ok=cs.filter(c=>c.status==="OK").length,pending=cs.filter(c=>!["OK","KO","Storno"].includes(c.status)).length,value=cs.reduce((s,c)=>s+Number(c.price||0),0),exp=cs.filter(c=>c.offerExpiry&&new Date(c.offerExpiry)>=new Date()&&new Date(c.offerExpiry)<=new Date(Date.now()+30*864e5)).length;return '<section class="stats"><div class="stat"><div class="stat-label">Contratti</div><div class="stat-value">'+total+'</div><div class="stat-note">Luce + Gas vale 2 contratti</div></div><div class="stat"><div class="stat-label">Contratti OK</div><div class="stat-value">'+ok+'</div><div class="stat-note">Pratiche valide</div></div><div class="stat"><div class="stat-label">In lavorazione</div><div class="stat-value">'+pending+'</div><div class="stat-note">Da verificare</div></div><div class="stat"><div class="stat-label">Valore offerte</div><div class="stat-value small-value">'+money(value)+'</div><div class="stat-note">'+exp+' in scadenza entro 30 giorni</div></div></section><div class="quick-grid"><button class="quick-card" id="quick-contract"><b>＋ Nuovo contratto</b><span>Inserisci una nuova pratica</span></button><button class="quick-card" id="quick-status"><b>◷ Controlla stati</b><span>Segui OK, KO e storni</span></button><button class="quick-card" id="quick-affiliate"><b>♧ Nuovo affiliato</b><span>Aggiungi un partner commerciale</span></button></div><div class="grid-2"><section class="panel"><div class="panel-head"><div><h2>Ultimi contratti</h2><div class="panel-sub">Le pratiche più recenti</div></div><button class="link-btn" data-go="contracts">Vedi tutti →</button></div>'+contractTable(cs.slice(-8).reverse())+'</section><section class="panel"><div class="panel-head"><div><h2>Attenzione</h2><div class="panel-sub">Attività da non dimenticare</div></div></div>'+alerts(cs)+'</section></div>'}
function alerts(cs){const today=new Date(), soon=cs.filter(c=>c.offerExpiry&&new Date(c.offerExpiry)>=today&&new Date(c.offerExpiry)<=new Date(Date.now()+30*864e5));if(!soon.length)return '<div class="empty compact">Nessuna scadenza nei prossimi 30 giorni.</div>';return '<div class="alert-list">'+soon.slice(0,6).map(c=>'<div class="alert-row"><div><b>'+esc(c.name)+'</b><span>'+esc(c.service)+' · '+esc(c.manager)+'</span></div><strong>'+esc(c.offerExpiry)+'</strong></div>').join("")+'</div>'}
function contractTable(list){if(!list.length)return '<div class="empty">Nessun contratto ancora. Inserisci il primo.</div>';return '<div class="table-wrap"><table><thead><tr><th>Cliente</th><th>Firma</th><th>Servizio</th><th>Gestore</th><th>Venditore</th><th>Prezzo</th><th>Stato</th><th></th></tr></thead><tbody>'+list.map(c=>'<tr><td><b>'+esc(c.name)+'</b><span class="subcell">'+esc(c.phone||"")+'</span></td><td>'+esc(c.date)+'</td><td>'+esc(c.service)+'</td><td>'+esc(c.manager)+'</td><td>'+esc(c.seller)+'</td><td>'+money(c.price)+'</td><td><span class="badge '+badge(c.status)+'">'+esc(c.status)+'</span></td><td><button class="icon-btn edit-contract" data-id="'+c.id+'">✎</button><button class="icon-btn delete-contract" data-id="'+c.id+'">×</button></td></tr>').join("")+'</tbody></table></div>'}
function badge(s){return s==="OK"?"ok":s==="KO"||s==="Storno"?"ko":"pending"}
function contracts(){return '<section class="panel"><div class="panel-head"><div><h2>Gestione contratti</h2><div class="panel-sub">Clienti, servizi, gestori, condizioni commerciali e stato pratica.</div></div><button class="primary" id="new-contract">+ Nuovo contratto</button></div><div class="filters"><input class="input grow" id="contract-search" placeholder="Cerca cliente, telefono, email..."><select class="select" id="contract-service">'+options(SERVICES,"","Tutti i servizi")+'</select><select class="select" id="contract-manager">'+options(MANAGERS,"","Tutti i gestori")+'</select><select class="select" id="contract-status">'+options(STATUSES,"","Tutti gli stati")+'</select></div><div id="contracts-table">'+contractTable(data.contracts.slice().reverse())+'</div></section>'}
function clients(){let list=data.contracts.slice();return '<section class="panel"><div class="panel-head"><div><h2>I miei clienti</h2><div class="panel-sub">Tutti i clienti associati alle tue pratiche.</div></div><div class="client-count"><b>'+list.length+'</b> clienti</div></div><div class="filters"><input class="input grow" id="client-search" placeholder="Cerca nome, email, telefono, città..."><select class="select" id="client-sort"><option value="new">Più recenti</option><option value="old">Più vecchi</option><option value="az">Nome A → Z</option><option value="za">Nome Z → A</option><option value="price-high">Prezzo più alto</option><option value="price-low">Prezzo più basso</option></select><select class="select" id="client-service">'+options(SERVICES,"","Tutti i servizi")+'</select><select class="select" id="client-manager">'+options(MANAGERS,"","Tutti i gestori")+'</select><select class="select" id="client-seller">'+options(visibleSellerNames(),"","Tutti i venditori")+'</select><select class="select" id="client-status">'+options(STATUSES,"","Tutti gli stati")+'</select></div><div id="clients-table">'+clientTable(list)+'</div></section>'}
function clientTable(list){if(!list.length)return '<div class="empty">Nessun cliente trovato.</div>';return '<div class="table-wrap"><table><thead><tr><th>Cliente</th><th>Email</th><th>Telefono</th><th>Città</th><th>Prezzo</th><th>Gestore</th><th>Data stipula</th><th>Servizio</th><th>Venditore</th><th>Stato</th><th>Email</th></tr></thead><tbody>'+list.map(c=>'<tr><td><b>'+esc(c.name)+'</b><span class="subcell">'+(c.birthday?("Compleanno: "+esc(c.birthday)):"")+'</span></td><td>'+esc(c.email||"—")+'</td><td>'+esc(c.phone||"—")+'</td><td>'+esc(c.city||"—")+'</td><td>'+money(c.price)+'</td><td>'+esc(c.manager)+'</td><td>'+esc(c.date)+'</td><td>'+esc(c.service)+'</td><td>'+esc(c.seller)+'</td><td><span class="badge '+badge(c.status)+'">'+esc(c.status)+'</span></td><td><button class="secondary send-welcome" data-id="'+esc(c.id)+'">Invia benvenuto</button></td></tr>').join("")+'</tbody></table></div>'}

function leads(){let l=data.leads.slice().sort((a,b)=>String(b.created||"").localeCompare(String(a.created||"")));return '<section class="panel"><div class="panel-head"><div><h2>Lead e opportunità</h2><div class="panel-sub">Clienti potenziali e possibili vendite da seguire fino alla chiusura.</div></div><button class="primary" id="new-lead">+ Nuovo lead</button></div><div class="lead-summary"><div><b>'+l.length+'</b><span>Lead totali</span></div><div><b>'+money(l.filter(x=>x.stage==="Caldo").reduce((s,x)=>s+Number(x.value||0),0))+'</b><span>Opportunità calde</span></div><div><b>'+l.filter(x=>x.stage==="Chiuso").length+'</b><span>Vendite chiuse</span></div></div><div class="filters"><input class="input grow" id="lead-search" placeholder="Cerca nome, telefono, email, città..."><select class="select" id="lead-stage"><option value="">Tutti gli stati</option><option>Nuovo</option><option>Contattato</option><option>Interessato</option><option>Caldo</option><option>Chiuso</option><option>Perso</option></select><select class="select" id="lead-service">'+options(SERVICES,"","Tutti i servizi")+'</select><select class="select" id="lead-seller">'+options(SELLERS,"","Tutti i venditori")+'</select></div><div id="leads-table">'+leadTable(l)+'</div></section>'}
function leadTable(list){if(!list.length)return '<div class="empty">Nessun lead. Inserisci la prima possibile vendita.</div>';return '<div class="table-wrap"><table><thead><tr><th>Cliente potenziale</th><th>Contatti</th><th>Servizio</th><th>Valore</th><th>Stato</th><th>Prossimo contatto</th><th>Venditore</th><th></th></tr></thead><tbody>'+list.map(x=>'<tr><td><b>'+esc(x.name)+'</b><span class="subcell">'+esc(x.city||"")+'</span></td><td>'+esc(x.phone||"—")+'<span class="subcell">'+esc(x.email||"")+'</span></td><td>'+esc(x.service||"—")+(x.manager?'<span class="subcell">'+esc(x.manager)+'</span>':"")+'</td><td>'+money(x.value)+'</td><td><span class="lead-stage '+(x.stage==="Caldo"?"hot":x.stage==="Chiuso"?"closed":x.stage==="Perso"?"lost":"open")+'">'+esc(x.stage)+'</span></td><td>'+esc(x.nextContact||"—")+'</td><td>'+esc(x.seller||"—")+'</td><td><button class="icon-btn edit-lead" data-id="'+x.id+'">✎</button><button class="icon-btn delete-lead" data-id="'+x.id+'">×</button></td></tr>').join("")+'</tbody></table></div>'}
function calendar(){let ev=data.events.slice().sort((a,b)=>(a.date+" "+a.time).localeCompare(b.date+" "+b.time));return '<section class="calendar-layout"><section class="panel"><div class="panel-head"><div><h2>Agenda Top House</h2><div class="panel-sub">Appuntamenti, richiami e note commerciali.</div></div><button class="primary" id="new-event">+ Nuovo appuntamento</button></div><div class="calendar-list">'+(ev.length?ev.map(x=>'<article class="event-card"><div class="event-date"><b>'+new Date(x.date+"T12:00").getDate()+'</b><span>'+new Date(x.date+"T12:00").toLocaleDateString("it-IT",{weekday:"short",month:"short"})+'</span></div><div class="event-main"><div><span class="event-type">'+esc(x.type)+'</span><h3>'+esc(x.title)+'</h3><p>'+esc(x.notes||"Nessuna nota")+'</p></div><div class="event-meta"><b>'+esc(x.time||"")+'</b><span>'+esc(x.client||"")+'</span></div></div><div class="event-actions"><button class="icon-btn edit-event" data-id="'+x.id+'">✎</button><button class="icon-btn delete-event" data-id="'+x.id+'">×</button></div></article>').join(""):'<div class="empty">Nessun appuntamento. Crea il primo dalla tua agenda.</div>')+'</div></section><aside class="panel agenda-tips"><h2>Da ricordare</h2><div class="tip"><b>📅 Appuntamenti</b><span>Segna ora, cliente e motivo dell’incontro.</span></div><div class="tip"><b>📝 Note</b><span>Salva le informazioni utili per il prossimo contatto.</span></div><div class="tip"><b>🔥 Lead</b><span>Trasforma i contatti interessati in opportunità.</span></div></aside></section>'}
function statsPage(){const now=new Date(),seller=statsSelectedSeller||data.contracts[0]?.seller||"Lamine Tall",months=[];for(let i=5;i>=0;i--){const d=new Date(now.getFullYear(),now.getMonth()-i,1),key=d.toISOString().slice(0,7),label=d.toLocaleDateString("it-IT",{month:"short",year:"numeric"}),n=data.contracts.filter(c=>String(c.date||"").slice(0,7)===key&&(c.seller||"")===seller).reduce((a,c)=>a+(c.service==="Luce + Gas"?2:1),0);months.push({label,n})}const mine=data.contracts.filter(c=>(c.seller||"")===seller),total=mine.reduce((a,c)=>a+(c.service==="Luce + Gas"?2:1),0),value=mine.reduce((a,c)=>a+Number(c.price||0),0),last=months[5]?.n||0,prev=months[4]?.n||0,diff=last-prev;return '<section class="stats"><div class="stat"><div class="stat-label">I miei contratti</div><div class="stat-value">'+total+'</div><div class="stat-note">Luce + Gas vale 2</div></div><div class="stat"><div class="stat-label">Questo mese</div><div class="stat-value">'+last+'</div><div class="stat-note">'+(diff>=0?"+":"")+diff+' rispetto al mese scorso</div></div><div class="stat"><div class="stat-label">Mese scorso</div><div class="stat-value">'+prev+'</div><div class="stat-note">Contratti acquisiti</div></div><div class="stat"><div class="stat-label">Valore totale</div><div class="stat-value small-value">'+money(value)+'</div><div class="stat-note">Delle pratiche di '+esc(seller)+'</div></div></section><section class="panel"><div class="panel-head"><div><h2>Andamento vendite</h2><div class="panel-sub">Ultimi 6 mesi · venditore: '+esc(seller)+'</div></div><select class="select" id="stats-seller">'+options(visibleSellerNames(),seller)+'</select></div><div class="bars">'+months.map(x=>'<div class="bar-col"><b>'+x.n+'</b><div class="bar" style="height:'+Math.max(8,x.n*28)+'px"></div><span>'+x.label+'</span></div>').join("")+'</div></section>'}
function usersPage(){
const manageable=userProfiles.filter(u=>u.active!==false&&((isAdmin())||(isManager()&&(u.uid===currentUser.uid||u.managerUid===currentUser.uid))));
 return '<section class="panel"><div class="panel-head"><div><h2>Utenti e ruoli</h2><div class="panel-sub">Crea credenziali, assegna ruoli e collega i venditori ai loro responsabili.</div></div>'+(isAdmin()?'<button class="primary" id="new-user">+ Crea credenziali</button>':'<span class="role-pill">Gestione sub-venditori</span>')+'</div><div class="role-grid">'+(manageable.map(u=>'<article class="user-card"><div><div class="user-name">'+esc(u.name||u.email)+'</div><div class="user-email">'+esc(u.email)+'</div></div><span class="role-tag role-'+esc(u.role)+'">'+esc(ROLE_LABELS[u.role]||u.role)+'</span><div class="user-meta"><span>Responsabile: <b>'+esc(u.managerName||"Nessuno")+'</b></span><span>'+((data.contracts||[]).filter(c=>c.seller===u.name).length)+' pratiche</span></div>'+(u.uid!==currentUser.uid&&isAdmin()?'<div class="user-actions"><button class="secondary edit-user" data-uid="'+u.uid+'">Modifica</button><button class="icon-btn delete-user" data-uid="'+u.uid+'">×</button></div>':'')+'</article>').join("")||'<div class="empty">Nessun utente configurato.</div>')+'</div></section>';
}
function openUser(existing){const u=existing||{},allowedRoles=isAdmin()?["admin","manager","seller"]:["seller"],managers=userProfiles.filter(x=>x.role==="manager"&&x.active!==false&&x.uid!==u.uid);const m=modal('<div class="modal-head"><div><div class="eyebrow">TOP HOUSE · RETE</div><h2>'+(existing?"Modifica utente":"Crea nuove credenziali")+'</h2></div><button class="close">×</button></div><form><div class="form-grid"><div class="field"><label>Nome e cognome *</label><input class="input" name="name" value="'+esc(u.name)+'" required></div><div class="field"><label>Email *</label><input class="input" name="email" type="email" value="'+esc(u.email)+'" '+(existing?'readonly':'required')+'></div>'+(existing?'':'<div class="field"><label>Password temporanea *</label><input class="input" name="password" type="password" minlength="6" required></div>')+'<div class="field"><label>Ruolo *</label><select class="select" name="role">'+options(allowedRoles,u.role||"seller")+'</select></div><div class="field"><label>Responsabile / capo venditore</label><select class="select" name="managerUid"><option value="">Nessuno</option>'+managers.map(x=>'<option value="'+x.uid+'" '+(x.uid===u.managerUid?'selected':'')+'>'+esc(x.name)+'</option>').join("")+'</select></div><div class="field"><label>Stato</label><select class="select" name="active"><option value="true" '+(u.active!==false?'selected':'')+'>Attivo</option><option value="false" '+(u.active===false?'selected':'')+'>Disattivato</option></select></div></div><div class="form-actions"><button type="button" class="secondary cancel">Annulla</button><button class="primary">'+(existing?"Salva modifiche":"Crea account")+'</button></div></form>');m.querySelector(".close").onclick=()=>closeModal(m);m.querySelector(".cancel").onclick=()=>closeModal(m);m.querySelector("form").onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),manager=userProfiles.find(x=>x.uid===f.get("managerUid"));try{if(existing){await setDoc(doc(db,"users",existing.uid),{name:f.get("name"),role:f.get("role"),managerUid:f.get("managerUid")||null,managerName:manager?.name||"",active:f.get("active")==="true"},{merge:true});toast("Utente aggiornato")}else{const cred=await createUserWithEmailAndPassword(secondaryAuth,f.get("email").trim(),f.get("password"));await setDoc(doc(db,"users",cred.user.uid),{email:f.get("email").trim(),name:f.get("name"),sellerName:f.get("name"),role:f.get("role"),managerUid:f.get("managerUid")||null,managerName:manager?.name||"",active:true,createdAt:serverTimestamp()});toast("Credenziali create")}await loadProfiles();closeModal(m);render()}catch(err){console.error(err);toast(authErrorMessage(err))}}}
function affiliates(){return '<section class="panel"><div class="panel-head"><div><h2>Affiliati e partner</h2><div class="panel-sub">CAF, agenzie, venditori e partner che generano produzione.</div></div><button class="primary" id="new-affiliate">+ Nuovo affiliato</button></div><div class="section-grid">'+(data.affiliates.map(a=>'<article class="affiliate-card"><div class="affiliate-top"><div><div class="affiliate-name">'+esc(a.name)+'</div><div class="affiliate-type">'+esc(a.type)+' · '+esc(a.status)+'</div></div><div class="percent">'+esc(a.percent)+'%</div></div><div class="panel-sub affiliate-note">'+esc(a.phone||"")+' '+esc(a.email||"")+'</div></article>').join("")||'<div class="empty">Nessun affiliato.</div>')+'</div></section>'}
function plans(){return '<section class="panel"><div class="panel-head"><div><h2>Piani compensi</h2><div class="panel-sub">Area dedicata ai piani della rete vendita.</div></div></div><div class="section-grid">'+data.plans.map(p=>'<article class="affiliate-card"><div class="affiliate-name">'+esc(p.name)+'</div><div class="affiliate-type">'+esc(p.description)+'</div><div class="plan-date">Ultimo aggiornamento: <b>'+esc(p.updated)+'</b></div><button class="secondary">Apri piano</button></article>').join("")+'</div></section>'}
function automationsPage(){return '<section class="panel"><div class="panel-head"><div><h2>Registro automazioni email</h2><div class="panel-sub">Invii di benvenuto, auguri e promemoria scadenza.</div></div><button class="secondary" id="refresh-automations">↻ Aggiorna registro</button></div><div class="filters"><select class="select" id="automation-type"><option value="">Tutte le automazioni</option><option value="welcome">Benvenuto</option><option value="birthday">Compleanno</option><option value="expiry">Scadenza offerta · cliente</option><option value="expiry-seller">Scadenza offerta · venditore</option></select><select class="select" id="automation-status"><option value="">Tutti gli stati</option><option value="sent">Inviata</option><option value="sending">In corso</option><option value="failed">Errore</option></select></div><div id="automation-table">'+automationTable(automationLogs)+'</div></section>'}
function automationTable(list){if(!list.length)return '<div class="empty">Nessun invio registrato. Gli invii effettuati dal sistema compariranno qui.</div>';return '<div class="table-wrap"><table><thead><tr><th>Data</th><th>Automazione</th><th>Cliente</th><th>Destinatario</th><th>Servizio</th><th>Stato</th><th>Dettaglio</th></tr></thead><tbody>'+list.map(x=>'<tr><td>'+esc(x.updatedAt||x.createdAt||x.scheduledFor||"—")+'</td><td>'+esc(({welcome:"Benvenuto",birthday:"Compleanno",expiry:"Scadenza · cliente","expiry-seller":"Scadenza · venditore"})[x.type]||x.type||"—")+'</td><td>'+esc(x.clientName||"—")+'</td><td>'+esc(x.recipient||x.clientEmail||"—")+'</td><td>'+esc(x.service||"—")+'</td><td><span class="badge '+(x.status==="sent"?"ok":x.status==="failed"?"ko":"pending")+'">'+esc(({sent:"Inviata",sending:"In corso",failed:"Errore"})[x.status]||x.status||"—")+'</span></td><td>'+esc(x.error||x.expiryDate||"—")+'</td></tr>').join("")+'</tbody></table></div>'}
function statusPage(){const all=data.contracts.slice().reverse(),counts=Object.fromEntries(STATUSES.map(s=>[s,all.filter(c=>c.status===s).length]));return '<section class="stats"><div class="stat"><div class="stat-label">Totale</div><div class="stat-value">'+all.length+'</div></div><div class="stat"><div class="stat-label">In lavorazione</div><div class="stat-value">'+(counts.Inserito+counts["In lavorazione"])+'</div></div><div class="stat"><div class="stat-label">OK</div><div class="stat-value">'+counts.OK+'</div></div><div class="stat"><div class="stat-label">KO / Storno</div><div class="stat-value">'+(counts.KO+counts.Storno)+'</div></div></section><section class="panel"><div class="panel-head"><div><h2>Stato delle pratiche</h2><div class="panel-sub">Filtra e aggiorna rapidamente le tue pratiche.</div></div><select class="select" id="status-filter">'+options(STATUSES,"","Tutti gli stati")+'</select></div><div id="status-table">'+statusTable(all)+'</div></section>'}
function statusTable(list){if(!list.length)return '<div class="empty">Nessun contratto trovato.</div>';return '<div class="table-wrap"><table><thead><tr><th>Cliente</th><th>Servizio</th><th>Gestore</th><th>Venditore</th><th>Scadenza</th><th>Stato</th></tr></thead><tbody>'+list.map(c=>'<tr><td><b>'+esc(c.name)+'</b></td><td>'+esc(c.service)+'</td><td>'+esc(c.manager)+'</td><td>'+esc(c.seller)+'</td><td>'+esc(c.offerExpiry||"—")+'</td><td><select class="status-select" data-id="'+c.id+'">'+options(STATUSES,c.status)+'</select></td></tr>').join("")+'</tbody></table></div>'}
async function loadAutomationLogs(){
  if(!authInstance||!firebaseAuthUser){automationLogs=[];const target=document.querySelector("#automation-table");if(target)target.innerHTML='<div class="empty">Per consultare il registro, accedi con un account Firebase autorizzato.</div>';return}
  try{const call=functionsApi.getFunctions(firebaseApp,"europe-west1");const fn=functionsApi.httpsCallable(call,"listAutomationLogs");const result=await fn({});automationLogs=result.data.logs||[];const target=document.querySelector("#automation-table");if(target)target.innerHTML=automationTable(automationLogs)}catch(err){console.error(err);const target=document.querySelector("#automation-table");if(target)target.innerHTML='<div class="empty">Registro non disponibile: verifica accesso e configurazione Firebase Functions.</div>'}
}
async function authenticateForAutomations(){
  if(firebaseAuthUser)return true;
  if(!authApi||!authInstance){toast("Servizio di autenticazione non ancora caricato");return false}
  const m=modal('<div class="modal-head"><div><div class="eyebrow">TOP HOUSE</div><h2>Accedi per inviare email</h2></div><button class="close">×</button></div><form><div class="field"><label>Email aziendale</label><input class="input" type="email" name="email" required autocomplete="username"></div><div class="field"><label>Password Firebase</label><input class="input" type="password" name="password" required autocomplete="current-password"></div><p class="panel-sub">Usa un account già creato in Firebase Authentication e associato a un profilo CRM autorizzato.</p><div class="form-actions"><button type="button" class="secondary cancel">Annulla</button><button class="primary">Accedi</button></div></form>');
  m.querySelector(".close").onclick=m.querySelector(".cancel").onclick=()=>closeModal(m);
  return await new Promise(resolve=>{m.querySelector("form").onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);try{const cred=await authApi.signInWithEmailAndPassword(authInstance,f.get("email"),f.get("password"));firebaseAuthUser=cred.user;closeModal(m);toast("Accesso autorizzato");resolve(true)}catch(err){toast("Accesso non riuscito: verifica email e password");resolve(false)}}});
}
async function sendWelcomeEmail(contractId){
  if(!await authenticateForAutomations())return;
  try{const call=functionsApi.getFunctions(firebaseApp,"europe-west1");const fn=functionsApi.httpsCallable(call,"sendWelcomeEmail");await fn({contractId:String(contractId)});toast("Email di benvenuto inviata");await loadAutomationLogs();if(currentPage==="automations")render()}catch(err){console.error(err);toast(err?.message||"Invio non riuscito")}
}
function bindPage(){
const byId=id=>document.querySelector("#"+id);
byId("new-user")?.addEventListener("click",()=>openUser());
document.querySelectorAll(".edit-user").forEach(button=>button.onclick=()=>openUser(userProfiles.find(user=>user.uid===button.dataset.uid)));
document.querySelectorAll(".delete-user").forEach(button=>button.onclick=async()=>{if(!confirm("Disattivare questo utente?"))return;try{await firestoreApi.setDoc(firestoreApi.doc(db,"users",button.dataset.uid),{active:false},{merge:true});await loadProfiles();render();toast("Utente disattivato")}catch(error){console.error(error);toast("Impossibile aggiornare l'utente")}});
document.querySelectorAll("[data-go]").forEach(button=>button.onclick=()=>setPage(button.dataset.go));
const top=byId("new-contract-top"),contract=byId("new-contract"),affiliate=byId("new-affiliate"),lead=byId("new-lead"),event=byId("new-event");
if(top)top.onclick=openContract;if(contract)contract.onclick=openContract;if(affiliate)affiliate.onclick=openAffiliate;if(lead)lead.onclick=openLead;if(event)event.onclick=openEvent;
byId("quick-contract")?.addEventListener("click",openContract);
document.querySelectorAll(".send-welcome").forEach(button=>button.onclick=()=>sendWelcomeEmail(button.dataset.id));byId("quick-status")?.addEventListener("click",()=>setPage("status"));byId("quick-affiliate")?.addEventListener("click",openAffiliate);
const search=byId("contract-search");
if(search){const filter=()=>{let list=data.contracts.slice().reverse(),q=search.value.toLowerCase(),service=byId("contract-service").value,manager=byId("contract-manager").value,status=byId("contract-status").value;if(q)list=list.filter(c=>(c.name+" "+c.phone+" "+c.email).toLowerCase().includes(q));if(service)list=list.filter(c=>c.service===service);if(manager)list=list.filter(c=>c.manager===manager);if(status)list=list.filter(c=>c.status===status);byId("contracts-table").innerHTML=contractTable(list);bindContractActions()};["contract-search","contract-service","contract-manager","contract-status"].forEach(id=>byId(id).addEventListener("input",filter));bindContractActions();}
const clientSearch=byId("client-search");
if(clientSearch){const filter=()=>{let list=data.contracts.slice(),q=clientSearch.value.toLowerCase(),sort=byId("client-sort").value,service=byId("client-service").value,manager=byId("client-manager").value,seller=byId("client-seller").value,status=byId("client-status").value;if(q)list=list.filter(c=>(c.name+" "+c.email+" "+c.phone+" "+c.city).toLowerCase().includes(q));if(service)list=list.filter(c=>c.service===service);if(manager)list=list.filter(c=>c.manager===manager);if(seller)list=list.filter(c=>c.seller===seller);if(status)list=list.filter(c=>c.status===status);if(sort==="new")list.sort((a,b)=>String(b.date).localeCompare(String(a.date)));if(sort==="old")list.sort((a,b)=>String(a.date).localeCompare(String(b.date)));if(sort==="az")list.sort((a,b)=>a.name.localeCompare(b.name,"it"));if(sort==="za")list.sort((a,b)=>b.name.localeCompare(a.name,"it"));if(sort==="price-high")list.sort((a,b)=>Number(b.price||0)-Number(a.price||0));if(sort==="price-low")list.sort((a,b)=>Number(a.price||0)-Number(b.price||0));byId("clients-table").innerHTML=clientTable(list);document.querySelectorAll(".send-welcome").forEach(button=>button.onclick=()=>sendWelcomeEmail(button.dataset.id))};["client-search","client-sort","client-service","client-manager","client-seller","client-status"].forEach(id=>byId(id).addEventListener("input",filter));}
const statusFilter=byId("status-filter");if(statusFilter)statusFilter.onchange=()=>{let list=data.contracts.slice().reverse();if(statusFilter.value)list=list.filter(c=>c.status===statusFilter.value);byId("status-table").innerHTML=statusTable(list);bindStatusActions()};
const statsSeller=byId("stats-seller");if(statsSeller)statsSeller.onchange=()=>{statsSelectedSeller=statsSeller.value;setPage("stats")};
const refreshAuto=byId("refresh-automations");if(refreshAuto)refreshAuto.onclick=async()=>{if(await authenticateForAutomations())await loadAutomationLogs()};
const autoType=byId("automation-type"),autoStatus=byId("automation-status");if(autoType&&autoStatus){const filterAuto=()=>{let list=automationLogs.slice();if(autoType.value)list=list.filter(x=>x.type===autoType.value);if(autoStatus.value)list=list.filter(x=>x.status===autoStatus.value);byId("automation-table").innerHTML=automationTable(list)};autoType.onchange=filterAuto;autoStatus.onchange=filterAuto;loadAutomationLogs()}
bindLeadActions();bindEventActions();bindStatusActions();
}
function bindContractActions(){document.querySelectorAll(".edit-contract").forEach(b=>b.onclick=()=>{const c=data.contracts.find(c=>c.id==b.dataset.id);if(c&&!canManageSeller(c.seller))return toast("Non hai i permessi per questa pratica");openContract(c)});document.querySelectorAll(".delete-contract").forEach(b=>b.onclick=()=>{const c=data.contracts.find(c=>c.id==b.dataset.id);if(c&&!canManageSeller(c.seller))return toast("Non hai i permessi per questa pratica");if(confirm("Eliminare questo contratto?")){data.contracts=data.contracts.filter(c=>c.id!=b.dataset.id);save();render();toast("Contratto eliminato")}})}
function bindStatusActions(){document.querySelectorAll(".status-select").forEach(s=>s.onchange=()=>{const c=data.contracts.find(x=>x.id==s.dataset.id);if(c){c.status=s.value;save();toast("Stato aggiornato");render()}})}
function modal(html){const w=document.createElement("div");w.className="modal-backdrop open";w.innerHTML='<div class="modal">'+html+"</div>";document.body.appendChild(w);return w}function closeModal(m){m.remove()}
function contractExtra(service,c){
const both=service==="Luce + Gas",luce=service==="Luce",gas=service==="Gas";
const mgr=(l,n,v)=>'<div class="field"><label>'+l+'</label><select class="select" name="'+n+'" required>'+options(MANAGERS,v,"Seleziona gestore")+'</select></div>';
const pr=(l,n,v)=>'<div class="field"><label>'+l+'</label><input class="input" name="'+n+'" type="number" min="0" step=".01" value="'+esc(v||"")+'" placeholder="Es. 49,90"></div>';
const dur=(l,n,v)=>'<div class="field"><label>'+l+'</label><select class="select" name="'+n+'">'+options(["6 mesi","1 anno","2 anni","3 anni","4 anni","5 anni","10 anni"],v,"Seleziona durata")+'</select></div>';
const offer=(l,n,v)=>'<div class="field"><label>'+l+'</label><select class="select" name="'+n+'" required>'+options(["Fisso","Variabile"],v,"Seleziona tipo offerta")+'</select></div>';
if(both)return mgr("Gestore luce","managerLight",c.managerLight||c.manager||"")+offer("Tipo offerta luce","offerTypeLight",c.offerTypeLight||c.offerType||"")+pr("Prezzo luce (€)","priceLight",c.priceLight)+dur("Durata offerta luce","durationLight",c.durationLight)+mgr("Gestore gas","managerGas",c.managerGas||c.manager||"")+offer("Tipo offerta gas","offerTypeGas",c.offerTypeGas||c.offerType||"")+pr("Prezzo gas (€)","priceGas",c.priceGas)+dur("Durata offerta gas","durationGas",c.durationGas);
if(luce)return mgr("Gestore luce","managerLight",c.managerLight||c.manager||"")+offer("Tipo offerta","offerTypeLight",c.offerTypeLight||c.offerType||"")+pr("Prezzo luce (€)","priceLight",c.priceLight||c.price)+dur("Durata offerta","durationLight",c.durationLight||c.duration);
if(gas)return mgr("Gestore gas","managerGas",c.managerGas||c.manager||"")+offer("Tipo offerta","offerTypeGas",c.offerTypeGas||c.offerType||"")+pr("Prezzo gas (€)","priceGas",c.priceGas||c.price)+dur("Durata offerta","durationGas",c.durationGas||c.duration);
return pr("Prezzo servizio (€)","priceService",c.priceService||c.price);
}
function openContract(existing){
const c=existing||{};

const m=modal('<div class="modal-head"><div><div class="eyebrow">TOP HOUSE</div><h2>'+(existing?"Modifica contratto":"Nuovo contratto")+'</h2></div><button class="close">×</button></div><form><div class="form-section"><h3>1 · Cliente</h3><div class="form-grid"><div class="field"><label>Nome e cognome *</label><input class="input" name="name" value="'+esc(c.name)+'" required></div><div class="field"><label>Telefono *</label><input class="input" name="phone" value="'+esc(c.phone)+'" type="tel" required></div><div class="field"><label>Email *</label><input class="input" name="email" value="'+esc(c.email)+'" type="email" required></div><div class="field"><label>Città *</label><input class="input" name="city" value="'+esc(c.city)+'" required></div><div class="field"><label>Data di nascita</label><input class="input" type="date" name="birthday" value="'+esc(c.birthday)+'"></div></div></div><div class="form-section"><h3>2 · Servizio principale</h3><div class="field"><label>Seleziona servizio *</label><select class="select" id="contract-service-choice" name="service" required>'+options(SERVICES,c.service,"Seleziona servizio")+'</select></div></div><div id="dynamic-contract"></div><div class="form-section"><h3>Pratica</h3><div class="form-grid"><div class="field"><label>Data firma *</label><input class="input" type="date" name="date" value="'+esc(c.date||new Date().toISOString().slice(0,10))+'" required></div><div class="field"><label>Data prossimo contatto</label><input class="input" type="date" name="nextContact" value="'+esc(c.nextContact)+'"></div><div class="field"><label>RID</label><select class="select" name="rid">'+options(["RID","No RID"],c.rid||"RID")+'</select></div><div class="field"><label>Stato</label><select class="select" name="status">'+options(STATUSES,c.status||"In lavorazione")+'</select></div><div class="field full"><label>Note</label><textarea class="input textarea" name="notes">'+esc(c.notes)+'</textarea></div></div></div><div class="form-actions"><button type="button" class="secondary cancel">Annulla</button><button class="primary">'+(existing?"Salva modifiche":"Salva contratto")+'</button></div></form>');
const service=m.querySelector("#contract-service-choice"),dynamic=m.querySelector("#dynamic-contract");
const draw=()=>{
const v=service.value;
if(!v){dynamic.innerHTML="";return}
dynamic.innerHTML='<div class="form-section"><h3>3 · Tipologia e condizioni</h3><div class="form-grid"><div class="field"><label>Tipologia cliente *</label><select class="select" name="segment" required>'+options(["Residenziale","Business"],c.segment,"Seleziona tipologia")+'</select></div>'+contractExtra(v,c)+'</div></div><div class="form-section"><h3>Fonte contratto</h3><div class="form-grid"><div class="field"><label>Fonte</label><select class="select" id="contract-source" name="source">'+options(SOURCES,c.source,"Seleziona fonte")+'</select></div><div class="field" id="affiliate-comp-wrap" style="display:none"><label>Compenso affiliato (€)</label><input class="input" name="affiliateComp" type="number" min="0" step=".01" value="'+esc(c.affiliateComp)+'"></div><div class="field"><label>Venditore *</label><select class="select" name="seller" required>'+options(visibleSellerNames(),canManageSeller(c.seller)?c.seller:(c.seller||visibleSellerNames()[0]))+'</select></div></div></div>';
const src=m.querySelector("#contract-source"),wrap=m.querySelector("#affiliate-comp-wrap");
const toggle=()=>wrap.style.display=(src.value==="Affiliato"||src.value==="Venditore")?"":"none";src.onchange=toggle;toggle();
};
service.onchange=draw;
draw();
m.querySelector(".close").onclick=()=>closeModal(m);m.querySelector(".cancel").onclick=()=>closeModal(m);
m.querySelector("form").onsubmit=e=>{
e.preventDefault();const f=new FormData(e.target),v=f.get("service");
const price=v==="Luce + Gas"?Number(f.get("priceLight")||0)+Number(f.get("priceGas")||0):(["Luce","Gas"].includes(v)?Number(f.get("priceLight")||f.get("priceGas")||0):Number(f.get("priceService")||0));
const obj={id:c.id||Date.now(),name:f.get("name"),phone:f.get("phone"),email:f.get("email"),city:f.get("city"),birthday:f.get("birthday")||"",date:f.get("date"),nextContact:f.get("nextContact"),service:v,segment:f.get("segment"),managerLight:f.get("managerLight"),managerGas:f.get("managerGas"),manager:f.get("managerLight")||f.get("managerGas"),offerTypeLight:f.get("offerTypeLight"),offerTypeGas:f.get("offerTypeGas"),offerType:v==="Luce + Gas"?"Fisso/Variabile":(f.get("offerTypeLight")||f.get("offerTypeGas")||""),priceLight:f.get("priceLight"),priceGas:f.get("priceGas"),price,priceService:f.get("priceService")||"",additionalServices:[],additionalPrices:{},durationLight:f.get("durationLight"),durationGas:f.get("durationGas"),duration:f.get("durationLight")||f.get("durationGas"),rid:f.get("rid"),status:f.get("status"),seller:f.get("seller")||currentProfile?.name,source:f.get("source"),affiliateComp:f.get("affiliateComp"),notes:f.get("notes")};
if(existing)Object.assign(existing,obj);else data.contracts.push(obj);save();closeModal(m);render();toast(existing?"Contratto aggiornato":"Contratto inserito correttamente")
}}

function bindLeadActions(){document.querySelectorAll(".edit-lead").forEach(b=>b.onclick=()=>{const x=data.leads.find(x=>x.id==b.dataset.id);if(x&&!canManageSeller(x.seller))return toast("Non hai i permessi per questo lead");openLead(x)});document.querySelectorAll(".delete-lead").forEach(b=>b.onclick=()=>{const x=data.leads.find(x=>x.id==b.dataset.id);if(x&&!canManageSeller(x.seller))return toast("Non hai i permessi per questo lead");if(confirm("Eliminare questo lead?")){data.leads=data.leads.filter(x=>x.id!=b.dataset.id);save();render();toast("Lead eliminato")}});const q=document.querySelector("#lead-search");if(q){const f=()=>{let l=data.leads.slice(),qv=q.value.toLowerCase(),st=document.querySelector("#lead-stage").value,sv=document.querySelector("#lead-service").value,se=document.querySelector("#lead-seller").value;if(qv)l=l.filter(x=>(x.name+" "+x.phone+" "+x.email+" "+x.city).toLowerCase().includes(qv));if(st)l=l.filter(x=>x.stage===st);if(sv)l=l.filter(x=>x.service===sv);if(se)l=l.filter(x=>x.seller===se);document.querySelector("#leads-table").innerHTML=leadTable(l);bindLeadActions()};["lead-search","lead-stage","lead-service","lead-seller"].forEach(id=>document.querySelector("#"+id)?.addEventListener("input",f))}}
function bindEventActions(){document.querySelectorAll(".edit-event").forEach(b=>b.onclick=()=>openEvent(data.events.find(x=>x.id==b.dataset.id)));document.querySelectorAll(".delete-event").forEach(b=>b.onclick=()=>{if(confirm("Eliminare appuntamento?")){data.events=data.events.filter(x=>x.id!=b.dataset.id);save();render();toast("Appuntamento eliminato")}})}
function openLead(existing){const x=existing||{};const m=modal('<div class="modal-head"><div><div class="eyebrow">TOP HOUSE · OPPORTUNITÀ</div><h2>'+(existing?"Modifica lead":"Nuovo lead")+'</h2></div><button class="close">×</button></div><form><div class="form-section"><h3>Cliente potenziale</h3><div class="form-grid"><div class="field"><label>Nome e cognome *</label><input class="input" name="name" value="'+esc(x.name)+'" required></div><div class="field"><label>Telefono</label><input class="input" name="phone" value="'+esc(x.phone)+'" type="tel"></div><div class="field"><label>Email</label><input class="input" name="email" value="'+esc(x.email)+'" type="email"></div><div class="field"><label>Città</label><input class="input" name="city" value="'+esc(x.city)+'"></div></div></div><div class="form-section"><h3>Possibile vendita</h3><div class="form-grid"><div class="field"><label>Servizio *</label><select class="select" name="service" required>'+options(SERVICES,x.service)+'</select></div><div class="field"><label>Gestore</label><select class="select" name="manager">'+options(MANAGERS,x.manager,"Nessun gestore")+'</select></div><div class="field"><label>Valore stimato (€)</label><input class="input" name="value" type="number" min="0" step=".01" value="'+esc(x.value)+'"></div><div class="field"><label>Stato</label><select class="select" name="stage">'+options(["Nuovo","Contattato","Interessato","Caldo","Chiuso","Perso"],x.stage||"Nuovo")+'</select></div><div class="field"><label>Venditore</label><select class="select" name="seller">'+options(visibleSellerNames(),canManageSeller(x.seller)?x.seller:(x.seller||visibleSellerNames()[0]))+'</select></div><div class="field"><label>Prossimo contatto</label><input class="input" type="date" name="nextContact" value="'+esc(x.nextContact)+'"></div><div class="field full"><label>Note</label><textarea class="input textarea" name="notes" placeholder="Esigenze, offerta da proporre, obiezioni...">'+esc(x.notes)+'</textarea></div></div></div><div class="form-actions"><button type="button" class="secondary cancel">Annulla</button><button class="primary">'+(existing?"Salva modifiche":"Salva lead")+'</button></div></form>');m.querySelector(".close").onclick=()=>closeModal(m);m.querySelector(".cancel").onclick=()=>closeModal(m);m.querySelector("form").onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),obj={id:x.id||Date.now(),created:x.created||new Date().toISOString(),name:f.get("name"),phone:f.get("phone"),email:f.get("email"),city:f.get("city"),service:f.get("service"),manager:f.get("manager"),value:f.get("value"),stage:f.get("stage"),seller:f.get("seller"),nextContact:f.get("nextContact"),notes:f.get("notes")};if(existing)Object.assign(existing,obj);else data.leads.push(obj);save();closeModal(m);render();toast(existing?"Lead aggiornato":"Lead inserito")}}
function openEvent(existing){const x=existing||{},today=new Date().toISOString().slice(0,10);const m=modal('<div class="modal-head"><div><div class="eyebrow">TOP HOUSE · AGENDA</div><h2>'+(existing?"Modifica appuntamento":"Nuovo appuntamento")+'</h2></div><button class="close">×</button></div><form><div class="form-grid"><div class="field full"><label>Titolo *</label><input class="input" name="title" value="'+esc(x.title)+'" placeholder="Es. Appuntamento cliente Rossi" required></div><div class="field"><label>Data *</label><input class="input" type="date" name="date" value="'+esc(x.date||today)+'" required></div><div class="field"><label>Ora</label><input class="input" type="time" name="time" value="'+esc(x.time||"09:00")+'"></div><div class="field"><label>Tipo</label><select class="select" name="type">'+options(["Appuntamento","Richiamo","Riunione","Nota","Altro"],x.type||"Appuntamento")+'</select></div><div class="field"><label>Cliente / Lead</label><input class="input" name="client" value="'+esc(x.client)+'" placeholder="Nome cliente"></div><div class="field full"><label>Note</label><textarea class="input textarea" name="notes" placeholder="Cosa devo ricordarmi?">'+esc(x.notes)+'</textarea></div></div><div class="form-actions"><button type="button" class="secondary cancel">Annulla</button><button class="primary">'+(existing?"Salva modifiche":"Salva appuntamento")+'</button></div></form>');m.querySelector(".close").onclick=()=>closeModal(m);m.querySelector(".cancel").onclick=()=>closeModal(m);m.querySelector("form").onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),obj={id:x.id||Date.now(),title:f.get("title"),date:f.get("date"),time:f.get("time"),type:f.get("type"),client:f.get("client"),notes:f.get("notes")};if(existing)Object.assign(existing,obj);else data.events.push(obj);save();closeModal(m);render();toast(existing?"Appuntamento aggiornato":"Appuntamento salvato")}}

function openAffiliate(){const m=modal('<div class="modal-head"><h2>Nuovo affiliato</h2><button class="close">×</button></div><form id="affiliate-form"><div class="form-grid"><div class="field"><label>Nome / Ragione sociale *</label><input class="input" name="name" required></div><div class="field"><label>Tipo</label><select class="select" name="type">'+options(["CAF","Agenzia","Venditore","Partner","Altro"])+'</select></div><div class="field"><label>Percentuale</label><input class="input" name="percent" type="number" min="0" max="100" step=".1"></div><div class="field"><label>Telefono</label><input class="input" name="phone" type="tel"></div><div class="field full"><label>Email</label><input class="input" name="email" type="email"></div><div class="field"><label>Stato</label><select class="select" name="status"><option>Attivo</option><option>Inattivo</option></select></div></div><div class="form-actions"><button type="button" class="secondary cancel">Annulla</button><button class="primary">Salva affiliato</button></div></form>');m.querySelector(".close").onclick=()=>closeModal(m);m.querySelector(".cancel").onclick=()=>closeModal(m);m.querySelector("form").onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);data.affiliates.push({id:Date.now(),name:f.get("name"),type:f.get("type"),percent:f.get("percent"),phone:f.get("phone"),email:f.get("email"),status:f.get("status")});save();closeModal(m);render();toast("Affiliato aggiunto")}}
async function startCRM(){
  currentUser={uid:"local-admin",email:"admin@tophouse.local"};
  currentProfile={uid:"local-admin",email:"admin@tophouse.local",name:"Lamine Tall",sellerName:"Lamine Tall",role:"admin",managerUid:null,managerName:"",active:true};
  userProfiles=[currentProfile];
  document.querySelector(".app-shell").style.display="";
  const nav=document.querySelector(".sidebar nav");
  if(nav&&!nav.querySelector("[data-page=users]"))nav.insertAdjacentHTML("beforeend",'<button class="nav-item" data-page="users">⚙ <span>Utenti e ruoli</span></button>');
  document.querySelectorAll(".nav-item").forEach(b=>b.onclick=()=>setPage(b.dataset.page));
  try{
    const local=JSON.parse(localStorage.getItem(KEY)||"null");
    if(local)data={...defaultData,...local};
  }catch(err){console.warn("Local data unavailable",err)}
  try { render(); } catch(err) {
    console.error("CRM render error",err);
    const target=document.querySelector("#page-content");
    if(target) target.innerHTML='<section class="panel"><h2>Errore di avvio CRM</h2><p>La schermata ha incontrato un errore JavaScript.</p><pre style="white-space:pre-wrap;overflow-wrap:anywhere"></pre></section>';
    const pre=document.querySelector("#page-content pre"); if(pre) pre.textContent=err?.stack||String(err);
  }

  // Il cloud viene caricato DOPO che l'interfaccia è già operativa.
  try{
    const firebase=await import("./firebase.js?v=20261008g");
    const fs=await import("https://www.gstatic.com/firebasejs/12.19.0/firebase-firestore.js");
    db=firebase.db;
    firebaseApp=firebase.app;
    authApi=await import("https://www.gstatic.com/firebasejs/12.19.0/firebase-auth.js");
    functionsApi=await import("https://www.gstatic.com/firebasejs/12.19.0/firebase-functions.js");
    authInstance=authApi.getAuth(firebaseApp);
    authInstance.onAuthStateChanged(user=>{firebaseAuthUser=user||null});
    firestoreApi=fs;
    const ref=fs.doc(db,"crmData","main");
    const snap=await fs.getDoc(ref);
    if(snap.exists()){
      data={...defaultData,...snap.data()};
      localStorage.setItem(KEY,JSON.stringify(data));
      render();
    }
    cloudReady=true;
    cloudUnsubscribe?.();
    cloudUnsubscribe=fs.onSnapshot(ref,snap=>{
      if(!snap.exists()||snap.metadata.hasPendingWrites)return;
      data={...defaultData,...snap.data()};
      localStorage.setItem(KEY,JSON.stringify(data));
      render();
    },err=>{console.warn("Firebase listener unavailable",err);cloudReady=false});
  }catch(err){
    console.warn("CRM cloud unavailable; local mode active",err);
    cloudReady=false;
  }
}
startCRM().catch(err=>{
  console.error("CRM startup error",err);
  document.querySelector(".app-shell").style.display="";
  try{render()}catch(renderErr){console.error("Render error",renderErr)}
});
